from medspacy.section_detection import SectionRule

mis_section_rules = [
    SectionRule(category="chief_complaint", literal="History of Present Illness"),
    SectionRule(category="chief_complaint", literal="HPI:"),
    SectionRule(category="chief_complaint", literal="HPI"),
    SectionRule(category="chief_complaint", literal="H.P.I."),
    SectionRule(category="chief_complaint", literal="H.P.I.:"),
    SectionRule(category="chief_complaint", literal="H/P/I"),
    SectionRule(category="chief_complaint", literal="H/P/I:"),
    SectionRule(category="chief_complaint", literal="Patient presents from:"),
    SectionRule(category="chief_complaint", literal="Patient presents from"),
    SectionRule(category="chief_complaint", literal="Patient presents:"),
    SectionRule(category="chief_complaint", literal="Patient presents"),
    SectionRule(category="observation_and_plan", literal="Differential diagnosis"),
    SectionRule(category="observation_and_plan", literal="Differential diagnosis:"),
    SectionRule(category="observation_and_plan", literal="ddx"),
    SectionRule(category="observation_and_plan", literal="ddx:"),
    SectionRule(category="hospital_course", literal="ED Events:"),
    SectionRule(category="hospital_course", literal="ED Events"),
    SectionRule(category="hospital_course", literal="ED Course"),
    SectionRule(category="hospital_course", literal="ED Course:"),
    SectionRule(category="hospital_course", literal="On the Floor:"),
    SectionRule(category="observation_and_plan", literal="Review of Systems"),
    SectionRule(category="observation_and_plan", literal="Review of Systems:"),
    SectionRule(category="social_history", literal="Social history reports"),
    SectionRule(category="social_history", literal="Social history includes"),
    SectionRule(category="family_history", literal="Family history includes"),
    SectionRule(category="family_history", literal="Family history reports"),
]
